package com.tcheckit.wsdl;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 2/21/2014 7:29:15 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
public class WS_Enums {

    public enum SoapProtocolVersion{
        	Default(0),
        	Soap11(1),
        	Soap12(2);
        
        private int code;
        
        SoapProtocolVersion(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static SoapProtocolVersion fromString(String str)
        {
            if (str.equals("Default"))
                return Default;
            if (str.equals("Soap11"))
                return Soap11;
            if (str.equals("Soap12"))
                return Soap12;
            return null;
        }
    }
    public enum flag{
        	activated(0),
        	deleted(1),
        	unactivated(2);
        
        private int code;
        
        flag(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static flag fromString(String str)
        {
            if (str.equals("activated"))
                return activated;
            if (str.equals("deleted"))
                return deleted;
            if (str.equals("unactivated"))
                return unactivated;
            return null;
        }
    }
    public enum typePhone{
        	android(0),
        	iphone(1),
        	autre(2);
        
        private int code;
        
        typePhone(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static typePhone fromString(String str)
        {
            if (str.equals("android"))
                return android;
            if (str.equals("iphone"))
                return iphone;
            if (str.equals("autre"))
                return autre;
            return null;
        }
    }
    public enum civility{
        	Mademoiselle(0),
        	Madame(1),
        	Monsieur(2);
        
        private int code;
        
        civility(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static civility fromString(String str)
        {
            if (str.equals("Mademoiselle"))
                return Mademoiselle;
            if (str.equals("Madame"))
                return Madame;
            if (str.equals("Monsieur"))
                return Monsieur;
            return null;
        }
    }
    public enum familyStatus{
        	single(0),
        	married(1),
        	separated(2),
        	divorced(3),
        	pacs(4);
        
        private int code;
        
        familyStatus(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static familyStatus fromString(String str)
        {
            if (str.equals("single"))
                return single;
            if (str.equals("married"))
                return married;
            if (str.equals("separated"))
                return separated;
            if (str.equals("divorced"))
                return divorced;
            if (str.equals("pacs"))
                return pacs;
            return null;
        }
    }
    public enum pushProvider{
        	gcm(0),
        	apns(1);
        
        private int code;
        
        pushProvider(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static pushProvider fromString(String str)
        {
            if (str.equals("gcm"))
                return gcm;
            if (str.equals("apns"))
                return apns;
            return null;
        }
    }
    public enum pageElementType{
        	text(0),
        	media(1);
        
        private int code;
        
        pageElementType(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static pageElementType fromString(String str)
        {
            if (str.equals("text"))
                return text;
            if (str.equals("media"))
                return media;
            return null;
        }
    }
    public enum paymentMethod{
        	paypal(0),
        	transfer(1);
        
        private int code;
        
        paymentMethod(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static paymentMethod fromString(String str)
        {
            if (str.equals("paypal"))
                return paypal;
            if (str.equals("transfer"))
                return transfer;
            return null;
        }
    }
    public enum answerStatusEnum{
        	submit(0),
        	validated(1),
        	refused(2);
        
        private int code;
        
        answerStatusEnum(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static answerStatusEnum fromString(String str)
        {
            if (str.equals("submit"))
                return submit;
            if (str.equals("validated"))
                return validated;
            if (str.equals("refused"))
                return refused;
            return null;
        }
    }
}
